### ISSUE TITLE
help

### ISSUE THREAD

**Issue by techwiz37** [praiman99/AutoScriptVPN-AIO#1]
HOST/DOMAIN NOT MATCHED..INSTALLATION WILL TERMINATED

**Comment by techwiz37** [comment]
padahal udh ku arahin ke ip vps

**Comment by praiman99** [comment]
Halo sore ka, mohon maaf nih sebelumnya karna telat membalas nya sip ane akan semak dan perbaiki masalah ini makasih nih udah melaporkan nya mohon maaf atas masalah yang belaku

**Comment by praiman99** [comment]
Halo malem ka ane udah perbaiki mohon di coba jika ada masalah mohon di beritahu iya

**Comment by techwiz37** [comment]
ok kutes dlu

**Comment by techwiz37** [comment]
yg full open source dijual?

**Comment by praiman99** [comment]
ga di jual ka

**Comment by techwiz37** [comment]
• VLESS TLS          : VLESS TLS Service is not running (Error)
 • TROJAN GFW         : TROJAN GFW Service is not running (Error)
 • VMESS NONE TLS     : VMESS NON TLS Service is not running (Error)
 • VLESS NONE TLS     : VLESS NON TLS Service is not running (Error)
 • XRAY VLESS XTLS

**Comment by techwiz37** [comment]
add-ws command not found. semua not found

**Comment by praiman99** [comment]
mohon maap karna telat pastikan udah os debian 9/10 kalo udah debian 9/10 di coba rebuilt kembali dan instalasi kembali
