### ISSUE TITLE
Domain/subdomain

### ISSUE THREAD

**Issue by kallipso** [praiman99/AutoScriptVPN-AIO#2]
hi
i got this error. i use domain.fun
HOST/DOMAIN NOT MATCHED..INSTALLATION WILL TERMINATED

**Comment by kallipso** [comment]
that work with domain.com

**Comment by praiman99** [comment]
Hi thanks for willing to contact us, first of all sorry for late reply because busy work. we wil fix this issue soon if we free time thanks for the report that issue

**Comment by praiman99** [comment]
Hi sir, I apologize in advance for our delay we have fixed the domain problem. we hope you can try again and give us feedback thank you very much for reporting the problem.

**Comment by kallipso** [comment]
Thanks :)
